### PR TITLE
Hyperlink tooltip

### PR DESCRIPTION
**Pull request by ahmedkrmn**
### Issue #100 
This PR replaces the JavaScript `alert` used when adding a hyperlink with a new tooltip as requested in the issue.

---

#### Old hyperlink input prompt:

-  _Text:_

    text

- _URL:_

    link

#### New input prompt:

- _Text & URL:_

    Screenshot (16)

### CODE REVIEW

**Comment by irmerk** [comment]
@michael-grover can you provide input? Want to see if this is in the right direction from a UX perspective.

**Comment by Michael-Grover** [comment]
@ahmedkrmn 

This looks great, thank you for taking this issue. Can you change the form field descriptions and placeholder text to the following:

**Link Text**
Text

**Link URL**
https://example.com 



Would it be possible for this UI to be placed above or below the text, so that it is easier for the user to tell which text is becoming a Hyperlink? See this example from Google Docs
image


@irmerk @DianaLease how do we ensure the styling of the buttons and the box around them can be adapted to Accord Project branding when this is placed in Template Studio V2?

**Comment by DianaLease** [comment]
> The functionality is a bit buggy at the moment, I recorded a Loom for reference:
> 
> https://www.loom.com/share/a17e17b6a89742e9b4268d87f3d0a107

IMO, the selection should stay highlighted when you click the link icon. When nothing is selected and you click the link icon, the cursor should remain so you know where the link will appear.

**Comment by irmerk** [comment]
@ahmedkrmn what's the status of this?

**Comment by ahmedkrmn** [comment]
@irmerk Hi Jolene,
I'm currently very busy, so if someone else wants to, they can continue working on this.

**Comment by irmerk** [comment]
Closing for now, used as context for #100

**Pull request closed without merging**
