### PR TITLE
style(FormattingToolbar, icons): improve markdown-editor UI/UX - I124

### PR DESCRIPTION
**Pull request by shrey-sachdeva2000**
Signed-off-by: Shrey Sachdeva <shreysachdeva.2000@gmail.com>

# Issue #124 
Polish markdown-editor overall UI/UX

### Proposed Changes
- Cleaning the toolbar with icons having equal proportions and similar style
- Increasing the editor width with more spacing for a cleaner look
- Removing header styles from dropdown for better accessibility
- Removing border color and radius that made the design look slightly unprofessional

### Flags
- Note that the changes will simultaneously need to be commited in `cicero-ui` and further in Clause template.

### Reference

UI

### CODE REVIEW

**Comment by shrey-sachdeva2000** [comment]
We can start working on this from here. @elit-altum

**Comment by elit-altum** [comment]
> 
> 
> We can start working on this from here. @elit-altum

Please provide contribution access.

**Comment by dselman** [comment]
When I preview the PR in Safari or Chrome the toolbar has some rendering issues.

Screenshot 2020-02-29 at 16 42 30

**Comment by irmerk** [comment]
> When I preview the PR in Safari or Chrome the toolbar has some rendering issues.

Yeah this seems to be a draft PR for the time being.

**Comment by shrey-sachdeva2000** [comment]
> When I preview the PR in Safari or Chrome the toolbar has some rendering issues.
> 
> Screenshot 2020-02-29 at 16 42 30

Sorry about that, this PR was for staging purposes. Will fix the issue in the next commits

**Comment by shrey-sachdeva2000** [comment]
**Changes**
- More subtle shadow on Formatting Toolbar and Markdown Wrapper
- New icons for Redo, Undo and Quote
- Changed background color to dark for Toolbar Tooltip
- Changed color for icons when active

**Issues**
- Toolbar Tooltip edge is still white, it might be coming from Slate

**Proposal**
- Mention the shortcut commands for the formatting options inside Tooltip
- Make the Tooltips more descriptive, "Add a link", "Insert code"

toolbar

**Comment by elit-altum** [comment]
Great work @shrey-sachdeva2000. I think you pretty much handled this one. I'll move to styling the ```ClausePlugin```

**Comment by irmerk** [comment]
Tagging @Michael-Grover and @DianaLease for feedback.

**Comment by Michael-Grover** [comment]
@shrey-sachdeva2000 please change the icons back to the originals

**Comment by shrey-sachdeva2000** [comment]
> **Proposal**
> 
> * Mention the shortcut commands for the formatting options inside Tooltip
> * Make the Tooltips more descriptive, "Add a link", "Insert code"

Please let me know your thoughts on this. @irmerk @Michael-Grover @DianaLease

**Comment by irmerk** [comment]
> **Proposal**
> 
> * Mention the shortcut commands for the formatting options inside Tooltip
> * Make the Tooltips more descriptive, "Add a link", "Insert code"

I like this proposal. Thoughts @Michael-Grover?

**Comment by Michael-Grover** [comment]
> > **Proposal**
> > 
> > * Mention the shortcut commands for the formatting options inside Tooltip
> > * Make the Tooltips more descriptive, "Add a link", "Insert code"
> 
> Please let me know your thoughts on this. @irmerk @Michael-Grover @DianaLease


Those sound good.

Can we show the shortcuts using this format?
image
image

Is it possible to detect what OS the user is running? So that we can change the shortcut based on that? On Windows use this format:  (Ctrl+B)

**Comment by irmerk** [comment]
Could potentially do "MOD" instead of "CMD" or "CTRL"

**Comment by Michael-Grover** [comment]
I wouldn't know what "MOD" means

**Comment by shrey-sachdeva2000** [comment]
> Is it possible to detect what OS the user is running? So that we can change the shortcut based on that? On Windows use this format: (Ctrl+B)

Sure, I'll try this out!

**Comment by 98lenvi** [comment]
@shrey-sachdeva2000  You can refer to [this](https://codepen.io/run-time/pen/XJNXWV) to get the platform(Linux/Windows/Mac). Just let me know if you want the react friendly version.

**Comment by elit-altum** [comment]
> @shrey-sachdeva2000 You can refer to [this](https://codepen.io/run-time/pen/XJNXWV) to get the platform(Linux/Windows/Mac). Just let me know if you want the react friendly version.

I think the tool tips have to be different only for 
1> MacOS
2> Hidden for mobile screens

You can also try ```navigator.appVersion``` or ```navigator.userAgent```

**Comment by shrey-sachdeva2000** [comment]
Please review #259 @irmerk @Michael-Grover. Thanks!

**Comment by Michael-Grover** [comment]
@shrey-sachdeva2000 is there somewhere I can preview this online? The Netlify preview in the list of checks isn't working.

**Comment by dselman** [comment]
> @shrey-sachdeva2000 is there somewhere I can preview this online? The Netlify preview in the list of checks isn't working.

For the `markdown-editor` you need to add `/examples` to the end of the Netlify URL:
https://deploy-preview-247--accordproject-markdown-editor.netlify.com/examples/

**Comment by Michael-Grover** [comment]
@dselman when I follow that link, I don't see @shrey-sachdeva2000 's changes

**Comment by shrey-sachdeva2000** [comment]
> @dselman when I follow that link, I don't see @shrey-sachdeva2000 's changes

I'm not sure why that is, [this](https://deploy-preview-247--accordproject-markdown-editor.netlify.com/examples/) link preview is working fine on my system. Caching could possibly be the issue here though.

**Comment by irmerk** [comment]
I believe @jeromesimeon fixed this in #253, just add `/examples` to the end of the Netlify link if it doesn't work for now.

**Comment by jeromesimeon** [comment]
> > @dselman when I follow that link, I don't see @shrey-sachdeva2000 's changes
> 
> I'm not sure why that is, [this](https://deploy-preview-247--accordproject-markdown-editor.netlify.com/examples/) link preview is working fine on my system. Caching could possibly be the issue here though. Should I attach a GIF?

You want to rebase with master, so you pick the latest fixes for netlify.

**Comment by jeromesimeon** [comment]
> > > @dselman when I follow that link, I don't see @shrey-sachdeva2000 's changes
> > 
> > 
> > I'm not sure why that is, [this](https://deploy-preview-247--accordproject-markdown-editor.netlify.com/examples/) link preview is working fine on my system. Caching could possibly be the issue here though. Should I attach a GIF?
> 
> ~You want to rebase with master, so you pick the latest fixes for netlify.~
> 
> Let me double check this. I thought we were in cicero-ui.

@shrey-sachdeva2000 yes :) I was correct. You should rebase with master so you get the correct configuration for netlify from this commit: https://github.com/accordproject/markdown-editor/commit/bb55a934e0f7b06f5d5da7dc77af7178c8dd8e2a

**Comment by shrey-sachdeva2000** [comment]
> @shrey-sachdeva2000 yes :) I was correct. You should rebase with master so you get the correct configuration for netlify from this commit: [bb55a93](https://github.com/accordproject/markdown-editor/commit/bb55a934e0f7b06f5d5da7dc77af7178c8dd8e2a)

Thanks @jeromesimeon. I'm now up-to-date with the master.
I hope it works now! @Michael-Grover

**Comment by jeromesimeon** [comment]
> > @shrey-sachdeva2000 yes :) I was correct. You should rebase with master so you get the correct configuration for netlify from this commit: [bb55a93](https://github.com/accordproject/markdown-editor/commit/bb55a934e0f7b06f5d5da7dc77af7178c8dd8e2a)
> 
> Thanks @jeromesimeon. I'm now up-to-date with the master.
> I hope it works now! @Michael-Grover

Did you push to this branch?

**Comment by jeromesimeon** [comment]
It's still 8 commits behind master

Screenshot 2020-03-04 at 12 07 32 PM

**Comment by shrey-sachdeva2000** [comment]
> Did you push to this branch?

I think I missed out on some steps, I'll take care in the future. I hope it works now!

**Comment by irmerk** [comment]
I'm not sure what happened with the rebase, but it is including older commits and I can't tell what is the code for this PR. I'd either fix that or open a new PR and close this one.

**Comment by shrey-sachdeva2000** [comment]
> I'm not sure what happened with the rebase, but it is including older commits and I can't tell what is the code for this PR. I'd either fix that or open a new PR and close this one.

Right, I kind of messed it up. Sorry about that. I think it would be best to move to a new PR?

**Comment by irmerk** [comment]
Yeah just link back to this one in the description for context.

**Comment by shrey-sachdeva2000** [comment]
Moved to #265 due to merge conflicts.

**Pull request closed without merging**
