### PR TITLE
feat(*): add toolbar button for images - I182

### PR DESCRIPTION
**Pull request by shrey-sachdeva2000**
Signed-off-by: Shrey Sachdeva <shreysachdeva.2000@gmail.com>

# Issue #182 
Added toolbar button for attaching images

### Changes
- New toolbar button for adding images
  - Added icon for the same

### Flags
- N/A

### CODE REVIEW

**Comment by shrey-sachdeva2000** [comment]
Please review @irmerk @Michael-Grover @DianaLease.
I have placed the icon in between the link and undo button, please let me know if that needs to be changed or the image icon svg needs to be something else.
Also, I have used the rendering method of `MarkButton` for now, this should call for another PR making this button functional.

**Comment by Michael-Grover** [comment]
This looks great, what are the next steps to making this button functional? @irmerk @DianaLease @shrey-sachdeva2000

**Comment by shrey-sachdeva2000** [comment]
> This looks great, what are the next steps to making this button functional? @irmerk @DianaLease @shrey-sachdeva2000

I believe it would be best to have both the functionalities Slate provides i.e., a popup to enter the URL when the user clicks on the image button (similar to what we have for links) and to handle and convert URL pasted in the markdown to images. Should I go ahead and create another issue for it?

**Comment by Michael-Grover** [comment]
sure thanks

**Comment by irmerk** [comment]
Actually based on this week I think we should hold off @shrey-sachdeva2000, @dselman is currently migrating `markdown-editor` to Slate `v0.5x`, which will be quite different than the version we're on. So I think it'll be helpful to put this on the back burner for a few days.

**Comment by shrey-sachdeva2000** [comment]
> Actually based on this week I think we should hold off @shrey-sachdeva2000, @dselman is currently migrating `markdown-editor` to Slate `v0.5x`, which will be quite different than the version we're on. So I think it'll be helpful to put this on the back burner for a few days.

Sure! @irmerk

**Comment by shrey-sachdeva2000** [comment]
Hi @irmerk! Based on the migration to Slate `v0.5x`, I think we can close this issue now.

**Pull request closed without merging**
