### PR TITLE
Polished border and added drop show to markdown editor

### PR DESCRIPTION
**Pull request by PseudoNerd**
# Issue #124
Polished editor border and added box shadow

### Changes
- Polished editor border and box shadow
  - Removed the border radius attribute and reduced the width.
  - Added a drop show effect to the markdown editor 

- changed appearance of the markdown editor.

### CODE REVIEW

**Comment by irmerk** [comment]
Closing as stale. Feel free to open back up if you come back to it.

**Comment by PseudoNerd** [comment]
Will this be opened again ?

**Comment by irmerk** [comment]
@PseudoNerd this is a duplicate of #148 at this point, correct?

**Comment by PseudoNerd** [comment]
Yes, that is true. 
There is no point in reopening this, to be honest.

**Pull request closed without merging**
