### PR TITLE
feat(hyperlink modal): fixed invalid url acceptance issue

### PR DESCRIPTION
**Pull request by nik72619c**
Signed-off-by: Nikhil <nikhilsharmarockstar21@gmail.com>

# Issue #365 
This PR adds the feature to validate whether the URL contains `http://` or `https://` in it.

### Changes
- Added logic for validating URL and maintained a state variable to show an error message
- Changed the placeholder from `https://example.com` to `example.com`

### CODE REVIEW

**Comment by shrey-sachdeva2000** [comment]
Hi @nik72619c! I think this would also rule out the possibility of adding links like this one `www.example.com` which is also a valid URL except the protocol `http` or `https` is decided later.

**Comment by nik72619c** [comment]
@DianaLease @shrey-sachdeva2000 I completely agree on this. But this was what @irmerk suggested as a comment on #365. Not sure if I interpreted wrong.

**Comment by irmerk** [comment]
> @DianaLease @shrey-sachdeva2000 I completely agree on this. But this was what @irmerk suggested as a comment on #365. Not sure if I interpreted wrong.

I was referring to inserting `https://` if none existed.

**Comment by nik72619c** [comment]
> > @DianaLease @shrey-sachdeva2000 I completely agree on this. But this was what @irmerk suggested as a comment on #365. Not sure if I interpreted wrong.
> 
> I was referring to inserting `https://` if none existed.

@irmerk thanks for clearing it out. updating this PR soon 👍

**Comment by nik72619c** [comment]
@DianaLease @irmerk please have a look

**Comment by Michael-Grover** [comment]
clicking on the link doesn't always seem to open the modal. I have to click a few times for it to open. Is that happening for anyone else? Try making the same line as I did into a link
image

**Comment by nik72619c** [comment]
> clicking on the link doesn't always seem to open the modal. I have to click a few times for it to open. Is that happening for anyone else? Try making the same line as I did into a link
> image

@Michael-Grover not able to reproduce this on my machine

**Comment by nik72619c** [comment]
@irmerk okay. Let me close this PR and file a new one with the changes.

**Pull request closed without merging**
