### PR TITLE
[WIP] feat(schema,ToolbarMethods): change in schema to allow nested list/quotes - #241

### PR DESCRIPTION
**Pull request by 98lenvi**
Signed-off-by: lenvi <lenvin@oykuapp.com>

# Issue #241 
Initial steps towards enabling nested quotes/list

### Changes
- Change in `Schema` & `ToolbarMethods`
  - `transformBlockQuoteToList` no longer unwraps the `block_quote` attribute, it justs wraps a `ol_list` (or) `ul_list` and `list_item` attributes over the existing.
  - `transformListToBlockQuote` no longer unwraps the `list_item` and `ol_list` (or) `ul_list` attribute, it justs wraps a `block_quote` attributes over the existing.
  - The modifications to the above two methods were only possible because of the changes I made in the `schema`, without `schema` changes the text would just disappear.

### Flags
- I want to know if changes to the `schema` are acceptable? If the current approach sounds good then I'll proceed
- I have commented out the code which isn't required anymore.

### Related Issues
- Issue #241

### CODE REVIEW

**Comment by irmerk** [comment]
I _believe_ this is the right direction. Would want feedback from @DianaLease and @dselman

**Comment by 98lenvi** [comment]
Okie! @DianaLease @irmerk I will try nesting lists in lists and block quotes in block quotes.

**Comment by 98lenvi** [comment]
Please don't look into this, I messed up when committing.

**Comment by irmerk** [comment]
Tag me when you're ready on this one, and if the rebasing issue is too difficult feel free to just open a new PR.

**Comment by 98lenvi** [comment]
@irmerk @DianaLease, I am still trying, but the issue (adding nested lists) is looking a bit complex, Right now you can create nested lists by pressing `Tab` twice (it does throw an error in the console).

Please go through the `list.js` plugin file, when adding `await` for the editor methods, the list disappears. It'll help me if you can share a link about the methods that can be called on the editor

**Comment by irmerk** [comment]
Could you actually start a new PR from a clean version of master with your current code? I really can't tell what is what in this PR with the old commits.

Docs for the methods which can be called on the editor: https://docs.slatejs.org/v/v0.47/

**Comment by 98lenvi** [comment]
@irmerk, Sorry about that. I'll make the changes in a new PR, then I'll tag you in that PR.

**Comment by 98lenvi** [comment]
@irmerk Please check #262

**Pull request closed without merging**
