### PR TITLE
feat(*): add styling for blockquote - I102

### PR DESCRIPTION
**Pull request by pramodrhegde**
# Issue #102
 Ability to style the blockquote text via a prop

### Changes
- Added `BLOCKQUOTE` prop under `editorProps`
  - `BLOCKQUOTE` prop can be used to style blockquotes in the document. `BLOCKQUOTE` prop supports following styles as of now: 

    - `FONT_FAMILY`
    - `FONT_COLOR`
    - `FONT_SIZE`
    - `FONT_STYLE`
    - `FONT_WEIGHT`
    - `QUOTE_COLOR`

Feature in action:

Screen Shot 2019-10-15 at 1 11 17 AM

### Flags
- The current props system for the blockquote is only for the text portion of the quote not for the entire quote itself, which includes styles for pseudoselectors.

### Related Issues
- Issue #102

### CODE REVIEW

**Comment by irmerk** [comment]
@pramodrhegde definitely will get to reviewing this, just working on another part of `markdown-editor` and want to get that through before I come back to review this.

**Comment by irmerk** [comment]
Tagging @Michael-Grover for review as well.

Looks good to me, great addition! Will want another review on this.

**Comment by Michael-Grover** [comment]
@pramodrhegde this looks great, thanks for adding! 

I think the bar on the left of the quote looks a bit thick, is that related to this issue or a separate issue?

**Comment by pramodrhegde** [comment]
@irmerk @Michael-Grover You guys are awesome! thank you :) It's my pleasure that I could contribute to this project.

@Michael-Grover You are right, the bar on the left of blockquote is not part of this change.
let me know if that needs a change, I can do that as a part of this PR.

**Comment by Michael-Grover** [comment]
@pramodrhegde can you change the width to 3px please?

**Pull request merged**
