### PR TITLE
fix(*): Selecting list/quote option while link popup is open crashes demo - #266

### PR DESCRIPTION
**Pull request by 98lenvi**
Signed-off-by: lenvi <lenvin@oykuapp.com>

# Issue #266 
Now the web app doesn't crash when list options are selected when the link popover is open

### Changes
- Making using of `isOnlyLink(editor)` from `toolbarMethods` to decide if any change shoud proceed in the markdown editor
 
### Flags
- Can be improved If I figure out a way to increase the selection area when the selection is only a list

### Related Issues
- Issue #266
- Pull Request #268

### CODE REVIEW

**Comment by DianaLease** [comment]
For some reason I'm not seeing the netlify preview option for this PR. anyone else having this issue?

**Comment by jeromesimeon** [comment]
> For some reason I'm not seeing the netlify preview option for this PR. anyone else having this issue?

Maybe because it's on the new `development` branch. Let me see if I can figure that out.

**Comment by jeromesimeon** [comment]
> > For some reason I'm not seeing the netlify preview option for this PR. anyone else having this issue?
> 
> Maybe because it's on the new `development` branch. Let me see if I can figure that out.

Added the `development` branch to the netlify deployment. It probably won't take effect until the next change to it though (and still not sure how it will behave on PRs). I'll keep monitoring.

**Comment by irmerk** [comment]
@98lenvi maybe try to force push again? Could kickstart the netlify preview process.

**Comment by 98lenvi** [comment]
@irmerk, Well, I made an empty commit, by doing so I just pushed a commit and due to a [known GitHub bug](https://github.com/isaacs/github/issues/1157) it looks like I dismissed the reviews(Which I didn't).

**Comment by DianaLease** [comment]
I am going to close this PR as this is no longer an issue after the Slate migration.

**Pull request closed without merging**
