### PR TITLE
chore(*): comment out underline-related code - I97

### LINKED ISSUE #97: Remove Underline Button from Toolbar
Since transitioning to [utilize the `markdown-transform`](https://github.com/accordproject/markdown-editor/releases/tag/v0.6.0), we will need to take a step back from supporting underline for the time being. Markdown doesn't natively support underline, so we need to rethink how we serialise this. 

Remove the underline option for now

We can then experiment with using `html` tags for underline.

### Related issues: 
- #81

### PR DESCRIPTION
**Pull request by cmccandless**
# Issue #97
Remove underline button from toolbar

### Changes
- Comment out references to underline (left as placeholders for whenever #98 is resolved)

### Related Issues
- Issue #98

Resolves #97

### CODE REVIEW

**Comment by cmccandless** [comment]
Works just fine:
image
Bold, Italic, etc buttons still work as well.

**Comment by cmccandless** [comment]
If anything, there is a slightly noticeable extra spacing created by the grid.

**Comment by cmccandless** [comment]
Latest commit fixes the extra spacing:
image

**Comment by irmerk** [comment]
Right, I think we also need to be editing the CSS to accommodate for this. I hope we get a solution in for handling underline soon, but in case we don't, we want the toolbar to not look like something is missing.

**Comment by cmccandless** [comment]
@irmerk If there are no other changes to request, can you please mark approval?

**Comment by irmerk** [comment]
You'll need to correct the DCO on your last commit.

**Comment by cmccandless** [comment]
@irmerk done

**Pull request merged**
