### PR TITLE
[WIP] feat(schema,plugin): nested items - #241

### PR DESCRIPTION
**Pull request by 98lenvi**
# Issue #241 
Changes for allowing nested lists (nested quotes, lists in quotes, quotes in lists will be added shortly)

### Changes
- Added `ul_list` and `ol_list` as children of `list_item` in `schema.js`
-Added a new method, `onTab` for handling creation of nested lists,
-Added support for lists in quotes, quotes in lists via `schema` changes and editing `transformBlockQuoteToList` & `transformListToBlockQuote`
### Flags
  -There is an error whenever a user presses `Tab`, **a nested list is only created when a user presses `Tab` twice**, and the nested list should be only created when the text-cursor is placed right after the list item symbol, not when it is in the middle of the list text.
  - the error generated is `Uncaught (in promise) Error: Item node should not occur outside of List nodes`
  - I will work on adding the other nesting features, then tackle the above issues.

### Related Issues
- Issue #241 
- Pull Request #250 
- Pull Request #261 (That was a mistake)

### CODE REVIEW

**Comment by irmerk** [comment]
This looks good so far!

A couple user actions are a bit buggy I think. In the demo do these two procedures:

1. Scroll to the ordered list
2. Click on "two"
3. Click block quote three times.

1. Scroll to the ordered list
2. Click on "two"
3. Click block quote once (should be a block quote in an ordered list now)
4. While selecting "two", press tab

**Comment by 98lenvi** [comment]
@irmerk , Thanks for pointing that one out!

**Comment by DianaLease** [comment]
I think it would be best to solve the error you mentioned in "flags" before moving on. Once that error occurs, I can no longer edit any part of the document.

**Comment by 98lenvi** [comment]
Okay! I guess I'll have to think from a different approach to solve that.

**Comment by 98lenvi** [comment]
@irmerk @DianaLease. I have done a **hack** to solve the double tab issue, but I don't think it's the right approach, everything other than the nested list is working. I think for now only supporting nested quotes, lists in quotes and quotes in lists is possible from my end. 

I'll work on the nested lists once I get some more experience in slate.js, Sorry :disappointed:

**Comment by 98lenvi** [comment]
@irmerk @DianaLease, I'm done with the bug-fixes and also nested lists are working fine :100:. Please check it out and let me know if there are any more bugs.

**Comment by irmerk** [comment]
It looks like your rebase was botched and there's at least one `<<<<<<< HEAD` remaining and it's failing the tests. Try cleaning that up for a clean build and we can look at it

**Comment by Michael-Grover** [comment]
image

The indentation between different levels of nesting looks very long.

Check out Google Docs and Word for reference

image
image

**Comment by 98lenvi** [comment]
> It looks like your rebase was botched and there's at least one `<<<<<<< HEAD` remaining and it's failing the tests. Try cleaning that up for a clean build and we can look at it

Can you please help me with this, I have no idea how to fix it without ruining my patches.

**Comment by 98lenvi** [comment]
> This is coming along well. We will also need a way to outdent once in a nested list item to go back a level. Commonly, `shift + tab` is used for this. Right now in this PR, that command causes further nesting.

Okay I

> This is coming along well. We will also need a way to outdent once in a nested list item to go back a level. Commonly, `shift + tab` is used for this. Right now in this PR, that command causes further nesting.

I have added support for outdenting lists, please look into it

**Comment by 98lenvi** [comment]
@Michael-Grover, I think the _long identation_ might be because of the way I'm creating nested lists, 
via our plugin, the markdown for a nested list would be
- main list item 1
- - nested list item 1
  - nested list item 2
- main list item 2

Ideally, it should be 

- main list item 1
  - nested list item 1
  - nested list item 2
- main list item 2

Once I properly create lists I guess the long indentation issue should be fixed

**Comment by 98lenvi** [comment]
@DianaLease, I think using `SHIFT`+`TAB` isn't a good option, because when using that key combo, the following happens:
shift_tab

**Comment by Michael-Grover** [comment]
> @DianaLease, I think using `SHIFT`+`TAB` isn't a good option, because when using that key combo, the following happens:
> shift_tab

This is because clicking tab in the editor changes focus to the next element instead of actually adding a tab, right? Is that a separate issue?

**Comment by DianaLease** [comment]
I just tried shift + tab on the lists again in the netlify on this PR and now it is working as expected to outdent the list item! Did something change? @98lenvi

**Comment by 98lenvi** [comment]
@DianaLease, I didn't change anything. The behavior is only in my browser, works fine everywhere else.

**Comment by 98lenvi** [comment]
> > @DianaLease, I think using `SHIFT`+`TAB` isn't a good option, because when using that key combo, the following happens:
> > shift_tab
> 
> This is because clicking tab in the editor changes focus to the next element instead of actually adding a tab, right? Is that a separate issue?

@Michael-Grover, Yes I think that's the cause

**Comment by irmerk** [comment]
This is great progress, but I think like a few other PRs in `markdown-editor`, we should put it on the backburner while we migrate to the latest Slate version. This will be implemented quite differently, and thus continuing work on this will only add to the complexity of migration.

**Comment by dselman** [comment]
Agreed. I'm going to close this one - we will work on it for Slate 0.50 - which doesn't really have the concept of a declarative schema.

**Pull request closed without merging**
