### PR TITLE
fix(FormattingToolbar): toolbar buttons work in locktext mode

### PR DESCRIPTION
**Pull request by Ian-Yy**
# Issue #122 
Currently, formatting tools such as Bold, Italic is working although lockText is true.

### Changes
Added checking on Editable before calling toggleMark

### CODE REVIEW

**Comment by irmerk** [comment]
I'm testing this locally and it looks like all the buttons work within a clause template.

**Comment by Ian-Yy** [comment]
Is it? I tested fine earlier. Let me retest it again

**Comment by Ian-Yy** [comment]
> I'm testing this locally and it looks like all the buttons work within a clause template.

I can't seem to simulate this. Bold, Italic button doesn't work when I'm in the clause template
But I found another issue that it's not reacting to lockText. Will fix this.

**Comment by Ian-Yy** [comment]
@irmerk I'm sorry but can you try again?

**Comment by irmerk** [comment]
Still isn't working for me. Loom recording here: https://www.loom.com/share/075f3393ebe44af79bde0ebb8a078c9f

@DianaLease could you try this locally?

**Comment by DianaLease** [comment]
> Still isn't working for me. Loom recording here: https://www.loom.com/share/075f3393ebe44af79bde0ebb8a078c9f
> 
> @DianaLease could you try this locally?

Running this locally and using npm link to use it in cicero-ui, I see the correct behavior. I cannot apply styles to locked text within a clause.

**Comment by DianaLease** [comment]
> But I found another issue that it's not reacting to lockText. Will fix this.

This seems to work for me. `lockText` only affects the text within a clause. So when lockText is true, you should not be able to style locked text within a clause, but you should still be able to style other contract text, which is what is happening in this PR.

Looks good!

**Comment by Ian-Yy** [comment]
Thank you for checking it and merging it up! 😄

**Pull request merged**
