### PR TITLE
feat(RichTextEditor): handle breaking from list - I335

### LINKED ISSUE #335: Lists Break on Enter
**Describe the bug**
Pressing <kbd>Enter</kbd> on an item in the List doesn't create a new item in the List.

**To Reproduce**
1. Go to the [demo](https://accordproject-markdown-editor.netlify.com/)
2. Click on a List item
3. Press <kbd>Enter</kbd>
4. A new line is created instead of List item

**Expected behavior**
On pressing <kbd>Enter</kbd>, a new list item should be created. While, on pressing <kbd>Shift+Enter</kbd> a new line within the same item should be created.

**Screenshots**
lists

### PR DESCRIPTION
**Pull request by irmerk**
# Closes #335
Handle adding new list items

### Changes
- New HOF to handle list logic
- On enter, if in a `list_item`, create and insert a new `list_item`

### Flags
- N/A

### Related Issues
- Issue #321
- Pull Request #350

### CODE REVIEW

**Comment by Michael-Grover** [comment]
https://www.loom.com/share/fed85a7d07e441db8a8e7ef145f20cc9

It looks like quote blocks can't be escaped. If I press enter in a quote block it creates another quote block, and if I press enter again, my cursor just moves back into the previous quote block, creating a loop. Does this need another issue? Do you know if we've already defined expected behavior for this?

@irmerk

**Comment by irmerk** [comment]
Yeah open a new issue with `Slate57` label @Michael-Grover

**Comment by shrey-sachdeva2000** [comment]
I think there is also no mechanism currently to enter a new line in the same list item. Google Docs and other editors handle this with `Shift+Enter`. Should I open a new issue for this? @irmerk

**Comment by Michael-Grover** [comment]
@shrey-sachdeva2000 Yes I think this makes sense. That is how Microsoft Word handles the issue as well

**Comment by irmerk** [comment]
Agreed, yes that should be a new Issue.

**Pull request merged**
