### PR TITLE
fix(SlateAsInputEditor): Make Editor Unobtrusive - I175

### PR DESCRIPTION
**Pull request by V1shvesh**
Add a fixed height and a scroll behaviour on overflow.

Signed-off-by: V1shvesh <22243137+V1shvesh@users.noreply.github.com>

# Issue #175 
This PR solves the issue of the Editor Scrollbar barging on top of the Toolbar by modifying the styles of EditorWrapper.

### Related Issues
- Issue #175

### CODE REVIEW

**Comment by irmerk** [comment]
@Michael-Grover I made a [Loom](https://www.loom.com/share/f4245afe7588431e80ceea2188c64797) of what this looks like now.

**Comment by Michael-Grover** [comment]
Hi @V1shvesh , thank you for taking on this issue. I think having the scrollbar inside of the page dilutes the visual metaphor of the white space as a page, and make it appear more like a window. We would like to keep the movement of the page the way it was, just changing the location of the scrollbar.

Here are two mockups of what I have in mind:

image

When the right pane is hidden:
image

Let me know if I can give any more detail

**Comment by irmerk** [comment]
Referencing my comment here: https://github.com/accordproject/markdown-editor/issues/175#issuecomment-548512127

I think we need to figure out how to implement either 2 or 3. This PR is doing 1, which isn't the direction we should be going in.

**Comment by V1shvesh** [comment]
@Michael-Grover I'd try to implement the version you've proposed then. :+1:

**Comment by irmerk** [comment]
Closing as stale, feel free to come back to it @V1shvesh!

**Pull request closed without merging**
