### PR TITLE
feat(FormattingToolbar): modified link popover styles - I213

### PR DESCRIPTION
**Pull request by elit-altum**
Signed-off-by: elit-altum <manan.sharma311@gmail.com>

# Issue #213 #293 
Continues on https://github.com/accordproject/markdown-editor/pull/246 and adds a feature to copy the link text to the clipboard by providing a 'copy' button.
Only displayed while editing the link.

### Changes
- Adds a new button to copy the link text to the clipboard.

### ScreenShot
copy-linkText-to-Clipboard

### Flags
- The UI looks bad. Really need @Michael-Grover's help to fix the layout, as three buttons will take lots of space. (Maybe use icons only?)

### Related Issues
- Pull Request #246 
- Pull Request #284

### CODE REVIEW

**Comment by elit-altum** [comment]
Continues #284 
Please review !

**Comment by elit-altum** [comment]
@DianaLease @Michael-Grover I have updated the button styles as mentioned in the in-vision project

**Comment by irmerk** [comment]
This will need to wait until https://github.com/accordproject/markdown-editor/issues/297 is finished (as well as https://github.com/accordproject/cicero-ui/issues/357) and then we can adapt and fold it in.

**Comment by irmerk** [comment]
@elit-altum:

#297 has been finished, so there is no longer a blocker on this issue. Confer with @DianaLease who is working on getting the hyperlink modal support again. #302 is tracking this.

**Comment by DianaLease** [comment]
Hi @elit-altum - The link modal has been migrated to slate 0.57. I'd suggest rebasing locally or restarting based off of the current master, as both the file structure as well as the link logic and rendering has changed to support the new slate version.

**Comment by elit-altum** [comment]
> 
> 
> Hi @elit-altum - The link modal has been migrated to slate 0.57. I'd suggest rebasing locally or restarting based off of the current master, as both the file structure as well as the link logic and rendering has changed to support the new slate version.

Sure @DianaLease I'll handle this asap. Sorry for being late I am a bit caught up in my online exams.
Thank you for the guidance!

**Comment by elit-altum** [comment]
Moving to https://github.com/accordproject/markdown-editor/pull/351

**Pull request closed without merging**
