### PR TITLE
Add option to hide markdown pane

### PR DESCRIPTION
**Pull request by johnnyqbui**
Signed-off-by: J <johnnyqbui7@gmail.com>

# Issue #23 
Add option to toggle display of markdown editor.

### Changes
- Add `display` prop to `MarkdownAsInputEditor`
  - add `display PropTypes`
- Cleaned up code
- Add `display` prop which takes a boolean to toggle display of markdown editor.

### Flags
- <DESCRIBE ISSUES OR HOLDS FOR REVIEWERS>

### Related Issues
- Issue #79 
- Issue #112

### CODE REVIEW

**Comment by irmerk** [comment]
@dselman and @DianaLease, I was thinking issue #23 was more about functionality, not necessarily about just the demo having this?

**Comment by DianaLease** [comment]
> @dselman and @DianaLease, I was thinking issue #23 was more about functionality, not necessarily about just the demo having this?

We don't have a single component that includes both panes. The demo is loading both panes as separate components, so I think the demo is the only place this functionality makes sense, unless I am misunderstanding something.

**Comment by irmerk** [comment]
> We don't have a single component that includes both panes. The demo is loading both panes as separate components, so I think the demo is the only place this functionality makes sense, unless I am misunderstanding something.

I suspect the issue is just outdated, I remember early on there being an idea of having the capability of switching between the markdown and the rich text?

**Comment by DianaLease** [comment]
> I suspect the issue is just outdated, I remember early on there being an idea of having the capability of switching between the markdown and the rich text?

Yes, I believe this issue is no longer relevant.

**Comment by irmerk** [comment]
I'm closing the issue and this PR. Apologies @johnnyqbui, but you're already getting all the swag for Hacktoberfest so hopefully this isn't too frustrating.

**Comment by johnnyqbui** [comment]
@irmerk ok no worries, ill look for another issue to work on. Thanks!

**Pull request closed without merging**
