### PR TITLE
enchancement(SlateAsInputEditor): change multiple if condition to sin…

### PR DESCRIPTION
**Pull request by 98lenvi**
…gle switch - #248

Signed-off-by: lenvi <lenvin@oykuapp.com>

# Issue #248 
Changed multiple if conditions to a single switch

### Changes
- I went with a single switch instead of two nested switches for better readability

### Flags
- Let me know if there is a more efficient way. To my best knowledge, I came up with this

### Related Issues
- Issue #248

### CODE REVIEW

**Comment by irmerk** [comment]
This is definitely an improvement. I was thinking of an object literal instead of a switch case - though I'm not 100% it's possible in this application.

A couple resources: 
- https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals
- https://dev.to/lukyhenson/replace-your-switch-statement-and-multiple-if-and-else-using-object-literals-en-us-1dec

**Comment by 98lenvi** [comment]
Wow @irmerk , Thanks for the resource . I never knew about object literal . Thank you once again

**Comment by irmerk** [comment]
Sure thing. Try that out and see if we can get rid of this switch case.

**Comment by 98lenvi** [comment]
@irmerk I tried but wasn't able to get rid of the switch. I'll try it later with a clear mind

**Comment by elit-altum** [comment]
@98lenvi if its okay with you, can I give this a shot?

**Comment by DianaLease** [comment]
This looks good to me! I'd say maybe we can merge this and then if someone wants to do further refactoring they can go from there?

**Comment by 98lenvi** [comment]
@elit-altum, I think you can open a new issue and try it out. Please do mention me in that issue, I'd love to know the solution/approach taken. Thanks!

**Comment by irmerk** [comment]
I reopened #248 if you want to continue @elit-altum

**Pull request merged**
