### PR TITLE
feat(HyperlinkModal): changed the UI and added icons - I213-293

### PR DESCRIPTION
**Pull request by elit-altum**
Signed-off-by: elit-altum <manan.sharma311@gmail.com>

# Issue #213 #293 
Continues on https://github.com/accordproject/markdown-editor/pull/246 and adds a feature to copy the link text to the clipboard by providing a 'copy' button.
Only displayed while editing the link.

### Changes
- Adds a new button to copy the link text to the clipboard.
- Modifies the current Hyperlink-UI

### ScreenShot
image

### Related Issues
- Pull Request #246 
- Pull Request #284

### CODE REVIEW

**Comment by Michael-Grover** [comment]
Looks great, huge improvement! But noticed the tooltips are missing for the buttons are missing

See the description of https://github.com/accordproject/markdown-editor/issues/293

> When a user hovers over one of the icons, there will be a hover effect like in the formatting toolbar, and a tooltip will appear stating what the button does.

> Copy link
> Delete link
> Open link in new tab
> https://projects.invisionapp.com/d/main#/console/16741009/409459590/preview
> image

**Comment by elit-altum** [comment]
> 
> 
> Looks great, huge improvement! But noticed the tooltips are missing for the buttons are missing
> 
> See the description of #293
> 
> > When a user hovers over one of the icons, there will be a hover effect like in the formatting toolbar, and a tooltip will appear stating what the button does.
> 
> > Copy link
> > Delete link
> > Open link in new tab
> > https://projects.invisionapp.com/d/main#/console/16741009/409459590/preview
> > image

Thank you @Michael-Grover 
I had asked a doubt here at https://github.com/accordproject/markdown-editor/pull/284#issuecomment-601348747 

@DianaLease Could you please help?

**Comment by DianaLease** [comment]
> Thank you @Michael-Grover
> I had asked a doubt here at [#284 (comment)](https://github.com/accordproject/markdown-editor/pull/284#issuecomment-601348747)
> 
> @DianaLease Could you please help?

I think let's get this in first and then those tooltips can be a separate issue. Is that alright with you, @Michael-Grover?

@elit-altum, can you rebase with master & address the conflicts? Make sure not to override the new functionality that was recently added for disabling the Apply button if the url field is empty please, please.

**Comment by Michael-Grover** [comment]
sure doing it without tooltips for now is fine

**Comment by elit-altum** [comment]
@DianaLease @irmerk I have addressed the merge conflicts. I was careful with #346 's changes as well!

**Comment by elit-altum** [comment]
@Michael-Grover @DianaLease @irmerk I have implemented the tooltips as well and I would suggest that we should handle them separately in a new issue + PR as the tooltip messages and functionalities would need some discussion.

Here is a preview using the Semantic-UI Popup component (created on a separate branch)
New-Tooltips
 
Thank You!

**Comment by DianaLease** [comment]
> @Michael-Grover @DianaLease @irmerk I have implemented the tooltips as well and I would suggest that we should handle them separately in a new issue + PR as the tooltip messages and functionalities would need some discussion.

@elit-altum Great! Can you open a new PR for those and we can discuss there? Thanks!

**Comment by elit-altum** [comment]
> Amazing! This one's not a big deal, but try to keep commit messages like [5b85e34](https://github.com/accordproject/markdown-editor/commit/5b85e342bbfe92d850602d66a5da02703433ea7e) to be in our format.
> 
> @DianaLease could you review also as a second

Really sorry for this @irmerk. I'll surely keep this in mind!

**Pull request merged**
