### PR TITLE
Readme : add keyboard shortcuts - #244

### PR DESCRIPTION
**Pull request by 98lenvi**
# Issue #244 
Updated readme to show the new keyboard shortcuts
### Changes
- The readme has the following text added just before the ###Demo section
------------------------------------------------
### Keyboard shortcuts

The keyboard shortcuts are as follows

- Common actions
  - `CTRL` + `C` - Copy
  - `CTRL` + `X` - Cut
  - `CTRL` + `V` - Paste
  - `CTRL` + `Z` - Undo
  - `CTRL` + `SHIFT` + `Z` - Redo
  - `CTRL` + `Y` - Repeat last action

- Text formatting
  - `CTRL` + `B` - Bold
  - `CTRL` + `I` - Italicize 
  - `CTRL` + `Q` - Block quotes
  - `CTRL` + `ALT` + `C` - Code

- Paragraph formatting
  - `CTRL` + `SHIFT` + `7` - Numbered list
  - `CTRL` + `SHIFT` + `8` - Bulleted list
----------------------------------------------------------

### Flags
- Should consider even more description like in [Google Docs](https://support.google.com/docs/answer/179738?co=GENIE.Platform%3DDesktop&hl=en)?, I don't think it's that necessary since Google's documentation is for consumers, while ours will be mostly read by developers/people witch technical expertise.

### Related Issues
- Issue #244

### CODE REVIEW

**Comment by Michael-Grover** [comment]
Can we include Apple shortcuts in the docs too? Using this symbol ⌘ instead of "Command" or "CMD"

Also, it looks like the shortcut for block quotes would be ⌘+Q, which is the same shortcut for quitting the application

image

**Comment by jeromesimeon** [comment]
> ### Flags
> * Should consider even more description like in [Google Docs](https://support.google.com/docs/answer/179738?co=GENIE.Platform%3DDesktop&hl=en)?, I don't think it's that necessary since Google's documentation is for consumers, while ours will be mostly read by developers/people witch technical expertise.
> 

I think keyboard shortcuts would be for users to use.

The better place for a documentation down the road would be in https://github.com/accordproject/techdocs

I would defer to @irmerk for how important this is/when to do it/how to track it.

**Comment by irmerk** [comment]
Yes I think once we get all the shortcuts decided on and the first iteration of the documentation done here, we can then work on porting it over into it's own section in the `techdocs` with it's own separate issue which references #244

**Comment by Michael-Grover** [comment]
Can we include the mac shortcuts too?

How is "CTRL + Q" the shortcut to add block quotes? Wouldn't that be ⌘ + Q which is the shortcut to quit an application?

**Comment by DianaLease** [comment]
This looks good once you add the Mac equivalents!

**Comment by 98lenvi** [comment]
Do you want the Mac shortcuts next to the Windows/Linux shortcuts
For example, 
  - `CTRL` + `C` / `CMD` + `C` - Copy

OR

Windows/Linux shortcuts in a separate section and Mac shortcuts in a separate section

Windows/Linux:
  - `CTRL` + `C` - Copy
  - .......

Mac:
  - `CMD` + `C` - Copy
  - .......

**Comment by 98lenvi** [comment]
@Michael-Grover, I can change the shortcut to some other key combination If you could suggest any other alternative combination it'd help. How about `SHIFT`+`Q`?

**Comment by Michael-Grover** [comment]
> Do you want the Mac shortcuts next to the Windows/Linux shortcuts
> For example,
> 
> * `CTRL` + `C` / `CMD` + `C` - Copy
> 
> OR
> 
> Windows/Linux shortcuts in a separate section and Mac shortcuts in a separate section
> 
> Windows/Linux:
> 
> * `CTRL` + `C` - Copy
> * .......
> 
> Mac:
> 
> * `CMD` + `C` - Copy
> * .......

Let's have them separate like the second option. And let's use ⌘ instead of "CMD"

**Comment by Michael-Grover** [comment]
> @Michael-Grover, I can change the shortcut to some other key combination If you could suggest any other alternative combination it'd help. How about `SHIFT`+`Q`?

Is there a reason the paragraph formatting shortcuts start at CTRL + SHIFT + 7? Can we use other numbers like CTRL + SHIFT + 6 for block quotes, or is that shortcut commonly used for something else?

**Comment by 98lenvi** [comment]
@Michael-Grover, It is used as _format as exponent_ in Google Sheets ( `CTRL`+`SHIFT`+`6` ), but we can use the same key combo for block quotes.

**Comment by 98lenvi** [comment]
I have updated it as below
----------------------------
### Keyboard shortcuts

The keyboard shortcuts are as follows

Windows/Linux:

- Common actions
  - `CTRL` + `C` - Copy
  - `CTRL` + `X` - Cut
  - `CTRL` + `V` - Paste
  - `CTRL` + `Z` - Undo
  - `CTRL` + `SHIFT` + `Z` - Redo
  - `CTRL` + `Y` - Repeat last action

- Text formatting
  - `CTRL` + `B` - Bold
  - `CTRL` + `I` - Italicize 
  - `CTRL` + `Q` - Block quotes
  - `CTRL` + `ALT` + `C` - Code

- Paragraph formatting
  - `CTRL` + `SHIFT` + `7` - Numbered list
  - `CTRL` + `SHIFT` + `8` - Bulleted list

Mac:

- Common actions
  - `⌘` + `C` - Copy
  - `⌘` + `X` - Cut
  - `⌘` + `V` - Paste
  - `⌘` + `Z` - Undo
  - `⌘` + `SHIFT` + `Z` - Redo
  - `⌘` + `Y` - Repeat last action

- Text formatting
  - `⌘` + `B` - Bold
  - `⌘` + `I` - Italicize 
  - `⌘` + `Q` - Block quotes
  - `⌘` + `ALT` + `C` - Code

- Paragraph formatting
  - `⌘` + `SHIFT` + `7` - Numbered list
  - `⌘` + `SHIFT` + `8` - Bulleted list

**Comment by Michael-Grover** [comment]
> @Michael-Grover, It is used as _format as exponent_ in Google Sheets ( `CTRL`+`SHIFT`+`6` ), but we can use the same key combo for block quotes.

that sounds good

**Comment by 98lenvi** [comment]
> > @Michael-Grover, It is used as _format as exponent_ in Google Sheets ( `CTRL`+`SHIFT`+`6` ), but we can use the same key combo for block quotes.
> 
> that sounds good

@Michael-Grover, I'll create a new issue for that and work on it, once that's done I'll update the key combo in the readme as well.

**Comment by Michael-Grover** [comment]
Cool thanks

**Comment by elit-altum** [comment]
Hey @98lenvi Could you look at https://github.com/accordproject/markdown-editor/issues/290 and update the shortcut for ```code``` in this PR?
Or should I open a new issue and PR @Michael-Grover and @irmerk ?

**Comment by 98lenvi** [comment]
@elit-altum. Sure!

**Comment by irmerk** [comment]
This looks good to go @98lenvi! Same as the other PR I just commented on, this is a bit unusual, but we're implementing a `development` branch to keep `master` more stable and for actual releases. Could you open a new PR but open it to merge this branch to `development` instead of `master`?

I posted more information about this in slack and will be updating the `CONTRIBUTING` and `DEVELOPERS` guides soon.

**Comment by 98lenvi** [comment]
Please refer #299

**Pull request closed without merging**
