### PR TITLE
feat(FormattingToolbar): support editing current links - I199

### PR DESCRIPTION
**Pull request by irmerk**
# Issue #199
Support editing a current link with the popup

### Changes
- Use pointer on hover over a link
- Add logic for if you click on a link
  - Move selection to this node to highlight all of it
  - Calculate the middle of this selection so that the caret of the popup shows in the middle
  - Link the text the user selected with the text inside the popup
- Handle editing a current link by unwrapping the link, deleting, and starting from scratch with a new link

### Flags
- Using the keyboard, moving to select the link highlights it all and disables further keyboard navigation
- ~Editing a current link will lose the cursor place~
- ~Highlighting a whole section / paragraph that includes a link only selects the link~
- ~Making bold *and* italic text a link crashes~

### [Deployed Netlify](https://deploy-preview-201--accordproject-markdown-editor.netlify.com/examples/)

### CODE REVIEW

**Comment by DianaLease** [comment]
This looks great! One thing I'm noticing when playing with it in the netlify is that _sometimes_ when I try to make/edit a second link, the text in the text box shows the text of the first link. I'm trying to pinpoint when exactly it happens...

**Comment by irmerk** [comment]
New flag: Click an existing link to edit, do not edit and only press enter, it crashes.

**Comment by dselman** [comment]
FYI on iOS (iPhone) clicking on a link moves the selection to the beginning or end of the link. Why do we need to modify the selection? Won’t this break keyboard navigation? For example, using right-arrow to move through the doc.

**Comment by dselman** [comment]
Modelling this on how Google Docs handles links would be best IMO - they don't modify the selection on keyboard presses, but they display a hover below the link so that it can be both opened and edited.

Screenshot 2019-11-22 at 07 55 52

**Comment by irmerk** [comment]
Another flag: There's a small edge case that when you are at the end of a link and `SHIFT + <-` to highlight the link, the popup does not have the url in it.

**Pull request merged**
